### ISSUE TITLE
Migrate w3c reference fetching to machine-readable endpoint

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-w3c#11]
We have been alerted that W3C publishes their bibdata here:
www.w3.org/2002/01/tr-automation/tr.rdf

By using this endpoint we ensure that the citations are always accurate.

We can parse this using gems that work with RDF.

Entries look like this:

```xml
    <CR rdf:about="https://www.w3.org/TR/2021/CRD-css-backgrounds-3-20210726/">
        <dc:date>2021-07-26</dc:date>
        <dc:title>CSS Backgrounds and Borders Module Level 3</dc:title>
        <doc:obsoletes rdf:resource="https://www.w3.org/TR/2020/CR-css-backgrounds-3-20201222/"/>
        <doc:versionOf rdf:resource="https://www.w3.org/TR/css-backgrounds-3/"/>
        <editor rdf:parseType="Resource">
            <contact:fullName>Bert Bos</contact:fullName>
        </editor>
        <editor rdf:parseType="Resource">
            <contact:fullName>Elika Etemad</contact:fullName>
        </editor>
        <editor rdf:parseType="Resource">
            <contact:fullName>Brad Kemper</contact:fullName>
        </editor>
        <implementationFeedbackDue>2021-07-27</implementationFeedbackDue>
        <org:deliveredBy rdf:parseType="Resource">
            <contact:homePage rdf:resource="https://www.w3.org/Style/CSS/"/>
        </org:deliveredBy>
        <patentRules rdf:resource="https://www.w3.org/Consortium/Patent-Policy-20040205/"/>
        <ED rdf:resource="https://drafts.csswg.org/css-backgrounds/"/>
    </CR>
```

**Comment by andrew2net** [comment]
The RDF source contains entries like:
```
    ...
    <Retired rdf:about="https://www.w3.org/TR/1999/WD-xmldsig-requirements-19991014">
        <rdf:type rdf:resource="http://www.w3.org/2001/02pd/rec54#WD"/>
        <dc:date>1999-10-14</dc:date>
        <dc:title>XML-Signature Requirements</dc:title>
        <doc:obsoletes rdf:resource="https://www.w3.org/1999/08/WD-xmldsig-requirements-990820.html"/>
        <doc:versionOf rdf:resource="https://www.w3.org/TR/xmldsig-requirements"/>
        <org:deliveredBy rdf:parseType="Resource">
            <contact:homePage rdf:resource="https://www.w3.org/2008/xmlsec/"/>
        </org:deliveredBy>
    </Retired>
    ...
```
I tried to select entries with SPARQL query:
```
PREFIX : <http://www.w3.org/2001/02pd/rec54#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?link ?title ?doctype
WHERE { ?link dc:title ?title ; rdf:type ?doctype . }
```
and got:
```
https://www.w3.org/TR/2001/NOTE-xmldsig-p3p-profile-20010202/, A P3P Assurance Signature Profile, http://www.w3.org/2001/02pd/rec54#NOTE
https://www.w3.org/TR/1999/WD-xmldsig-requirements-19991014, XML-Signature Requirements, http://www.w3.org/2001/02pd/rec54#Retired
https://www.w3.org/TR/1999/WD-xmldsig-requirements-19991014, XML-Signature Requirements, http://www.w3.org/2001/02pd/rec54#WD
https://www.w3.org/TR/2000/REC-DOM-Level-2-Events-20001113/, Document Object Model (DOM) Level 2 Events Specification, http://www.w3.org/2001/02pd/rec54#REC
...
```
The problem is the entries with `rdf:type` element are duplicated in the query result. In the result above there are 2 rows with the link `https://www.w3.org/TR/1999/WD-xmldsig-requirements-19991014` and different types: `http://www.w3.org/2001/02pd/rec54#Retired` and `http://www.w3.org/2001/02pd/rec54#WD`. It seems the first type is generated from the entrie's element name `Retired` and the second is `rdf:type@rdf:resource` atribute.
The question is how to query these 2 types in one row? For example `SELECT ?link ?title ?type1 ?type2`

**Comment by andrew2net** [comment]
@ronaldtse the RDF dataset contains only homepages for workgroups:
```
        <org:deliveredBy rdf:parseType="Resource">
            <contact:homePage rdf:resource="https://www.w3.org/WebPlatform/WG/"/>
        </org:deliveredBy>
```
The BibXML grammar required workgroup name:
```
IsoWorkgroup =
    attribute number { text }?,
    attribute type { text }?,
    attribute identifier { text }?,
    attribute prefix { text }?,
    text
```
Should we fetch the HTML pages and parse them to get the workgroups names?

**Comment by ronaldtse** [comment]
> Should we fetch the HTML pages and parse them to get the workgroups names?

Yes please. Thanks.

**Comment by ronaldtse** [comment]
We probably want to fetch all the WG names in one go and the correlate with the documents to prevent duplicated requests.

**Comment by ronaldtse** [comment]
From @andrew2net :
> it seems the RDF dataset doesn't contain obsoleted documents
> documents have relations to previous version but the related documents don't exist in the dataset

> 
> e.g. https://www.w3.org/TR/2015/WD-csp-pinning-20150226/
> 
> The document obsoleted by https://www.w3.org/TR/2016/NOTE-csp-pinning-20160913/ is not provided in this file.
> 
> ```
>     <NOTE rdf:about="https://www.w3.org/TR/2016/NOTE-csp-pinning-20160913/">
>         <rdf:type rdf:resource="http://www.w3.org/2001/02pd/rec54#Retired"/>
>         <dc:date>2016-09-13</dc:date>
>         <dc:title>Content Security Policy Pinning</dc:title>
>         <doc:obsoletes rdf:resource="https://www.w3.org/TR/2015/WD-csp-pinning-20150226/"/>
>         <doc:versionOf rdf:resource="https://www.w3.org/TR/csp-pinning/"/>
>         <editor rdf:parseType="Resource">
>             <contact:fullName>Mike West</contact:fullName>
>         </editor>
>         <org:deliveredBy rdf:parseType="Resource">
>             <contact:homePage rdf:resource="https://www.w3.org/2011/webappsec/"/>
>         </org:deliveredBy>
>         <ED rdf:resource="https://w3c.github.io/webappsec-csp/pinning/"/>
>     </NOTE>
> ```

**Comment by ronaldtse** [comment]
From @andrew2net

> Some groups referenced by the tr.rdf file cannot be referenced.
> I'm unable to find WG by the url https://www.w3.org/DOM/Group/ , which requires authentication.

https://www.w3.org/DOM/ says the group is closed, and apparently it is now hosted by WHATWG at https://dom.spec.whatwg.org. WHATWG is the new group that took away the DOM work from W3C.

I think we need to special case this group.

**Comment by ronaldtse** [comment]
@andrew2net please also see the old IETF implementation of this endpoint:
https://trac.ietf.org/trac/xml2rfc/browser/website/rfcs/bibxml/bibxml-w3c

**Comment by andrew2net** [comment]
@ronaldtse 

> @andrew2net please also see the old IETF implementation of this endpoint:
> https://trac.ietf.org/trac/xml2rfc/browser/website/rfcs/bibxml/bibxml-w3c

In the implementation a stdnumber is extracted from a URL:
```python
stdnumber = elroot.attrib.get(f'{RDF_NAMESPACE}about')
...
ret = os.path.basename(stdnumber)
```

For example the URL `https://www.w3.org/TR/1998/NOTE-html-lan-19980313` gives us the `NOTE-html-lan-19980313`stdnumber.
But there are URLs like `https://www.w3.org/TR/1998/REC-CSS2-19980512/fonts.html`. Should stdnumber be just `fonts` in this case? Are there any rules for W3C identifiers?

**Comment by ronaldtse** [comment]
@andrew2net there are no fixed rules for W3C identifiers. The above implementation is rather naive.

1. https://www.w3.org/TR/1998/REC-CSS2-19980512/fonts.html is Clause 15 of https://www.w3.org/TR/1998/REC-CSS2-19980512.
2. Its identifier should indicate a "sub-resource" or a "clause" of REC-CSS2-19980512.
3. Maybe something like `REC-CSS2-19980512#fonts` (a fragment) or just `REC-CSS2-19980512/fonts` (sub-resource). We don't want to use the `:` because it is often used with identifying the edition year.
