### ISSUE TITLE
Unable to cite "standard level" resource, only able to cite "version level" resource

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-w3c#18]
Any idea? Thanks!

```
[relaton-w3c] ("W3C TR shacl") fetching...
[relaton-w3c] ("W3C TR sparql11-query") fetching...
[relaton-w3c] ("W3C TR xmlschema-1") fetching...
[relaton-w3c] ("W3C TR xmlschema-2") fetching...
[relaton-w3c] ("W3C TR dx-connegp") fetching...
[relaton-w3c] ("W3C TR dx-prof") fetching...
[relaton-w3c] ("W3C TR turtle") fetching...
[relaton-w3c] ("W3C TR skos-reference") fetching...
[relaton-w3c] ("W3C XML Names") fetching...
[relaton-iso] ("ISO 8601-1") fetching...
[relaton-iso] ("ISO 690") fetching...
[relaton-iso] ("ISO 704") fetching...
[relaton-w3c] ("W3C TR vocab-adms") fetching...
[relaton-w3c] ("W3C TR shacl") not found.
[relaton-w3c] ("W3C TR sparql11-query") not found.
[relaton-w3c] ("W3C TR xmlschema-1") not found.
[relaton-w3c] ("W3C RDF") fetching...
[relaton-w3c] ("W3C OWL") fetching...
[relaton-w3c] ("W3C TR dx-connegp") not found.
[relaton-w3c] ("W3C TR xmlschema-2") not found.
[relaton-w3c] ("W3C TR turtle") not found.
[relaton-w3c] ("W3C TR vocab-adms") not found.
[relaton-w3c] ("W3C XML Names") not found.
[relaton-w3c] ("W3C TR skos-reference") not found.
[relaton-w3c] ("W3C OWL") not found.
[relaton-w3c] ("W3C RDF") not found.
[relaton-w3c] ("W3C TR dx-prof") not found.
```

**Comment by ronaldtse** [comment]
I know what the issue is now. Relaton-W3C is not reading the "versionOf" resource.

```console
$ grep xmlschema-1 tr.rdf 
    <WD rdf:about="https://www.w3.org/TR/2003/WD-xmlschema-11-req-20030121/">
        <doc:versionOf rdf:resource="https://www.w3.org/TR/xmlschema-11-req/"/>
    <REC rdf:about="https://www.w3.org/TR/2001/REC-xmlschema-1-20010502/">
        <doc:obsoletes rdf:resource="https://www.w3.org/TR/2001/PR-xmlschema-1-20010330/"/>
        <doc:versionOf rdf:resource="https://www.w3.org/TR/xmlschema-1/"/>
    <REC rdf:about="https://www.w3.org/TR/2004/REC-xmlschema-1-20041028/">
        <doc:obsoletes rdf:resource="https://www.w3.org/TR/2004/PER-xmlschema-1-20040318/"/>
        <doc:versionOf rdf:resource="https://www.w3.org/TR/xmlschema-1/"/>
        <previousEdition rdf:resource="https://www.w3.org/TR/2001/REC-xmlschema-1-20010502/"/>
```

Notice that every document resource (WD, REC) contains a `<doc:versionOf pdf:resource="...">` entry. This tells us that the `rdf:resource` is the parent identifier. i.e.

* https://www.w3.org/TR/xmlschema-1/ is the upper level resource (the standard)
* https://www.w3.org/TR/2004/REC-xmlschema-1-20041028 is a version resource (the standard edition)

We need to support citation of the standard level resource as well as the version level resource.

**Comment by ronaldtse** [comment]
There are several questions here we need to address them separately.

## Difference between an undated resource vs a dated resource

`xmlschema-1` we need to return the "undated" version of it, which links to the newest version. This is like the difference between ISO 123 vs ISO 123:2000.

There are:
* 1 undated resource through "versionOf"
  * `<doc:versionOf rdf:resource="https://www.w3.org/TR/xmlschema-1/"/>`
* 2 dated resources
  * `<REC rdf:about="https://www.w3.org/TR/2001/REC-xmlschema-1-20010502/">`
  * `<REC rdf:about="https://www.w3.org/TR/2004/REC-xmlschema-1-20041028/">`
* 2 inferred "obsoletedBy" resources:
  * `<doc:obsoletes rdf:resource="https://www.w3.org/TR/2001/PR-xmlschema-1-20010330/"/>`
  * `<doc:obsoletes rdf:resource="https://www.w3.org/TR/2004/PER-xmlschema-1-20040318/"/>`
 

## What stages are there in a W3C document?

* "REC" => W3C Recommendation
* "PER" => W3C Proposed Edited Recommendation
* "PR" => W3C Proposed Recommendation

<img width="643" alt="Screenshot 2022-02-13 at 11 57 57 AM" src="https://user-images.githubusercontent.com/11865/153738001-979aca00-f5e9-4437-864d-1fca34453146.png">
<img width="669" alt="Screenshot 2022-02-13 at 11 58 11 AM" src="https://user-images.githubusercontent.com/11865/153738010-cb323d8e-70ca-44b8-9f08-4220c6d33c35.png">
<img width="647" alt="Screenshot 2022-02-13 at 11 58 25 AM" src="https://user-images.githubusercontent.com/11865/153738017-30b0edd3-e0bf-461a-8404-d3ae2a0c54aa.png">
<img width="641" alt="Screenshot 2022-02-13 at 11 59 10 AM" src="https://user-images.githubusercontent.com/11865/153738029-5fc0bdac-88da-4522-a98a-bc4d95b4431d.png">

## What keywords do we allow searching for

* "TR" is the type of intended document. This is like "international-standard" in ISO.
  * The "type of document" should always be provided. If it is not provided, we default to "TR"
* "REC", "PER", "PR" are stages of the document. This is like "DIS" or "WD" in ISO.
  * The STAGE should always be provided if it is a "draft" (i.e. not "REC"). If no STAGE is provided, then we match to the newest version of the document.

We should also allow matching using URL (with or without trailing slash).

Example for Undated results (returns `https://www.w3.org/TR/xmlschema-1/`):
* `https://www.w3.org/TR/xmlschema-1/`
* `W3C TR xmlschema-1`
* `W3C xmlschema-1`
* `W3C TR REC xmlschema-1`
* `W3C REC xmlschema-1`

Example for Dated results (returns `https://www.w3.org/TR/2004/REC-xmlschema-1-20041028`): 
* `https://www.w3.org/TR/2004/REC-xmlschema-1-20041028`
* `W3C TR REC-xmlschema-1-20041028`
* `W3C REC-xmlschema-1-20041028`
* `W3C xmlschema-1-20041028`
* `W3C xmlschema-1 20041028`

**Comment by andrew2net** [comment]
> ## What keywords do we allow searching for
> * "TR" is the type of intended document. This is like "international-standard" in ISO.
>   
>   * The "type of document" should always be provided. If it is not provided, we default to "TR"
> * "REC", "PER", "PR" are stages of the document. This is like "DIS" or "WD" in ISO.
>   
>   * The STAGE should always be provided if it is a "draft" (i.e. not "REC"). If no STAGE is provided, then we match to the newest version of the document.

@ronaldtse what about NOTE (https://www.w3.org/TR/2017/NOTE-css-2017-20170131/)?

**Comment by ronaldtse** [comment]
* NOTE is a "type of document".

* "Retired" is a stage.

* "CR/Candidate Recommendation" is a stage. (https://www.w3.org/Consortium/Process-20010719/tr.html#RecsCR)

* "LastCall/Last Call Working Draft" is a stage. (https://www.w3.org/Consortium/Process-20010719/tr.html#last-call)

See ["Types of Technical Reports"](https://www.w3.org/2021/Process-20211102/#recs-and-notes):
<img width="841" alt="Screenshot 2022-03-29 at 5 56 38 AM" src="https://user-images.githubusercontent.com/11865/160493944-040104fc-eca1-4099-acb5-4193537910e3.png">

Recommendation track:
<img width="810" alt="Screenshot 2022-03-29 at 5 57 02 AM" src="https://user-images.githubusercontent.com/11865/160494057-17b7626d-3577-4828-ab63-49df8548630c.png">

Note track:
https://www.w3.org/2021/Process-20211102/#note-track
<img width="841" alt="Screenshot 2022-03-29 at 5 57 48 AM" src="https://user-images.githubusercontent.com/11865/160494136-5f8e4dfc-6b68-4915-bb29-4d8174e10536.png">

W3C Statement is a type of Note:
<img width="811" alt="Screenshot 2022-03-29 at 5 58 15 AM" src="https://user-images.githubusercontent.com/11865/160494193-67e489d5-11dc-42ba-ae15-4ad86884e0b4.png">

Registry track:
https://www.w3.org/2021/Process-20211102/#registries
<img width="822" alt="Screenshot 2022-03-29 at 5 59 03 AM" src="https://user-images.githubusercontent.com/11865/160494296-fa1ec099-49ef-4a7f-b5b0-1a4b8fdcad59.png">

In summary:
* Type of document: Recommendation, Note, Registry

* Recommendation maturity levels:

  * `FPWD` [First Public Working Draft](https://www.w3.org/2021/Process-20211102/#fpwd).
  * (optional) `WD` [Working Drafts](https://www.w3.org/2021/Process-20211102/#RecsWD).
  * `CR` [Candidate Recommendations](https://www.w3.org/2021/Process-20211102/#RecsCR)

    * CR Snapshot

    * CR Draft

    * Rescinded CR 
 
  * `PR` [Proposed Recommendation](https://www.w3.org/2021/Process-20211102/#RecsPR)
 
  * `REC` [W3C Recommendation](https://www.w3.org/2021/Process-20211102/#RecsW3C)

    * Superseded REC

    * Obsolete REC

    * Rescinded REC

  *  Discontinued Draft

  * Special draft status includes: "Patent Review Drafts" and "Last Call Working Draft"

* Note types

  * `NOTE` Group Note

  * Draft Note (can be multiple)

  * W3C Statement 

* Registry types

  * registry report

* Registry maturity stages

  * Draft Registry

  * Candidate Registry (equivalent to CR)

    * Candidate Registry Snapshot, Candidate Registry Draft

  * W3C Registry (equivalent to REC)

    * Obsolete Registry (equivalent to Obsolete REC), Superseded Registry (equivalent to Superseded REC)

    * (no equivalent to PR)

**Comment by andrew2net** [comment]
> Example for Undated results (returns `https://www.w3.org/TR/xmlschema-1/`):
> 
> * `https://www.w3.org/TR/xmlschema-1/`
> * `W3C TR xmlschema-1`
> * `W3C xmlschema-1`
> * `W3C TR REC xmlschema-1`
> * `W3C REC xmlschema-1`
> 
> Example for Dated results (returns `https://www.w3.org/TR/2004/REC-xmlschema-1-20041028`):
> 
> * `https://www.w3.org/TR/2004/REC-xmlschema-1-20041028`
> * `W3C TR REC-xmlschema-1-20041028`
> * `W3C REC-xmlschema-1-20041028`
> * `W3C xmlschema-1-20041028`
> * `W3C xmlschema-1 20041028`

@ronaldtse 
To be able to fetch all these references we need to make an index or extra files for reference variants.
I think an index isn't a good solution. It needs to fetch the entire index each time we fetch a document.
The extra files could be duplicates with the same content or with a redirection to document with the content.
Using redirection will need to make a second HTTP request, so it seems the better solution is to have many files for each document with the same content and different filenames. What do you think?

**Comment by ronaldtse** [comment]
I mean, an "index" shouldn't be a big deal? It's a couple KB, but it keeps the structure of the repo a lot cleaner than to have multiple copies of the document in the repo?

**Comment by andrew2net** [comment]
@ronaldtse two questions:
1. Do we need to create unversioned document if only one version of a document exists?
2. There are static [files](https://github.com/relaton/relaton-w3c/tree/main/data) that have [seriesInfo](https://github.com/relaton/relaton-w3c/blob/5c534d7c8020501aaa60876d3fa41b647d6f7301/data/reference.W3C.CR-rdf-schema.xml#L14) named "W3C" without version. BibXML parser uses the seriesInfo to create document identifier (PubID) but it conflicts with unversioned documents. For example in the [RDF](http://www.w3.org/2002/01/tr-automation/tr.rd) source there is a document `REC-xml-names-19990114`. In the static files there is a document with `<seriesInfo name="W3C" value="REC-xml-names"/>`. If we create unversioned document it will have the same PubID as the document from static files.

**Comment by ronaldtse** [comment]
> 1. Do we need to create an unversioned document if only one version of a document exists?

We should.

> 2. 

We should not store any BibXML. BibXML is an IETF format and is used by IETF only, we only want the data -- this means we have to massage (and manually fix) the data to the Relaton YAML format.

The point of using the old BibXML files are to fill in the missing data from the W3C RDF endpoint. If a corresponding item is already provided by the W3C RDF endpoint, we should throw away the corresponding item from the BibXML data source.

**Comment by andrew2net** [comment]
these references don't exist in the [RDF](http://www.w3.org/2002/01/tr-automation/tr.rd) source

> ```
> [relaton-w3c] ("W3C TR dx-connegp") not found.
> ...
> [relaton-w3c] ("W3C OWL") not found.
> [relaton-w3c] ("W3C RDF") not found.
> ```
