### ISSUE TITLE
Relaton model for W3C documents

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-w3c#2]
Do we have the mapping in PlantUML? Can we put it up in this repo?

**Comment by andrew2net** [comment]
@ronaldtse do you asking if we have W3C grammar? I don't see it in the metanorma-model-iso.

**Comment by ronaldtse** [comment]
Could you make a new relaton-model-w3c repo to contain this bibdata model?

**Comment by andrew2net** [comment]
Should the model inherit from `BibliographicItem`?

**Comment by ronaldtse** [comment]
Yes, it should. Thanks!
