### ISSUE TITLE
Store and parse historic bibliographic data (tr.rdf) from web.archive.org

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-w3c#24]
Look at:
https://web.archive.org/web/*/http://www.w3.org/2002/01/tr-automation/tr.rdf
<img width="1168" alt="Screenshot 2022-04-22 at 1 27 56 AM" src="https://user-images.githubusercontent.com/11865/164517115-0489fa42-3425-4db7-a2fc-ed09f3799138.png">

This is quite surprising -- since 2002 it was regularly scraped by web.archive.org.

In order to scrape full information for relaton-w3c-data, we can technically loop through every month (or every 3 months) of this history, and obtain the full history since 2002.

**Comment by andrew2net** [comment]
@ronaldtse do you mean we need to merge all historical versions of tr.rdf into relaton-data-w3c?

**Comment by ronaldtse** [comment]
@andrew2net yes that is the intent. Maybe we need to store these historical versions in some new Git repo, so we don't need to fetch them again and again.

**Comment by ronaldtse** [comment]
> historical versions

I meant the historic `td.rdf` files.

**Comment by andrew2net** [comment]
@ronaldtse I expressed wrong.
We can parse historical `tr.rdf` once and keep old files in the `relaton-data-w3c` repo. When just updating the old files and adding new from current `tr.rdf`.
Why do we need to parse the old `tr.rdf`s again and again?

**Comment by ronaldtse** [comment]
I've retrieved 1 copy per year from the last date I found in December.
[tr-archive-2002-2021.zip](https://github.com/relaton/relaton-w3c/files/8836599/tr-archive-2002-2021.zip)

**Comment by ronaldtse** [comment]
@andrew2net this issue is now urgent because of @strogonoff 's work on the IETF bibxml-service. We need to provide all historic information in relaton-data-w3c from now on.

For a single bibliography item that has gone through multiple stages, we will need to find a way to either encode its history in the same file, or use separate files. Possibly the first solution works better?

**Comment by ronaldtse** [comment]
@andrew2net this is blocking the BibXML Service's usage of W3C references. We need to fix this ASAP. Thanks.
