### ISSUE TITLE
When reading from cache of a "not found" entry, still show the warning that it was not found

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-w3c#29]
In building [ogc-modspec](https://github.com/metanorma/ogc-modspec), the following warnings are shown:
```
[relaton-w3c] ("W3C XML Schema Part 2") fetching...
[relaton-w3c] ("W3C XML Schema Part 1") fetching...
[relaton-w3c] ("W3C XML Schema Part 2") not found.
[relaton-w3c] ("W3C XML Schema Part 1") not found.
```

However, on the second run, these warnings are no longer shown because of the cache.

These warnings should always be shown even when read from cache to warn the user.

If this is a general issue across Relaton gems, please help implement this in the `relaton` gem proper.

**Comment by andrew2net** [comment]
fixed in general in the `relaton` gem
