### ISSUE TITLE
Support W3C document "status" and status abbreviations

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-w3c#3]
<img width="641" alt="Screen Shot 2020-03-18 at 9 32 28 AM" src="https://user-images.githubusercontent.com/11865/76916448-68a5d580-68fb-11ea-88b5-fcc53591e429.png">

CR => Candidate Recommendation
WD => Working Draft

Note => Group Note
<img width="327" alt="Screen Shot 2020-03-18 at 9 33 18 AM" src="https://user-images.githubusercontent.com/11865/76916491-81ae8680-68fb-11ea-828e-67e043378d46.png">

REC => Recommendation
<img width="313" alt="Screen Shot 2020-03-18 at 9 33 40 AM" src="https://user-images.githubusercontent.com/11865/76916507-8f640c00-68fb-11ea-9873-fce4cbd4c06f.png">

PR => Proposed Recommendation
<img width="311" alt="Screen Shot 2020-03-18 at 9 34 46 AM" src="https://user-images.githubusercontent.com/11865/76916544-b6224280-68fb-11ea-902e-bf6ed5f517b4.png">

PER => Proposed Edited Recommendation
<img width="334" alt="Screen Shot 2020-03-18 at 9 34 26 AM" src="https://user-images.githubusercontent.com/11865/76916537-aacf1700-68fb-11ea-9475-2f1a1dd3bdef.png">

ret => Retired

<img width="301" alt="Screen Shot 2020-03-18 at 9 35 05 AM" src="https://user-images.githubusercontent.com/11865/76916559-c0dcd780-68fb-11ea-8cc3-add3dd83a685.png">

**Comment by andrew2net** [comment]
fixed by ca498d600ab6f650ec311c835fa3f4f3381119a7
