### ISSUE TITLE
Contributor information is missing, compared to IETF’s `misc` source

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-w3c#32]
As an example:

- Here we have a contributor: https://github.com/ietf-tools/relaton-data-misc/blob/main/data/reference.W3C.xml-c14n.yaml
- Here (seemingly the same resource) we don’t have any contributors: https://github.com/ietf-tools/relaton-data-w3c/blob/main/data/xml-c14n.yaml

Since I don’t think we’d somehow lose contributor info, I presume this is caused by missing data in authoritative data supplied by W3C?

**Comment by ronaldtse** [comment]
See https://github.com/relaton/relaton-data-w3c/issues/6

This is resolved -- W3C has responded that they do **NOT** provide authoritative contributor and contact information from their API -- they do not store them. We should just omit them from now on.

**Comment by strogonoff** [comment]
This is a tricky situation for BibXML service. We could obsolete those misc items and map them to authoritative ones, but missing data makes it likely to cause complaints. Just as a note (@ronaldtse)

**Comment by ronaldtse** [comment]
@strogonoff agree with your note. I just don’t know what the best way to deal with this is. 

The problem only applies to the W3C references in the misc dataset, as the bibxml4 dataset does not provide contributor information anyway. 

As a last resort, we can “merge” the data between misc and W3C’s data but we don’t really want to do this for many reasons. 

I think we should just discourage people from using misc.

**Comment by strogonoff** [comment]
> I think we should just discourage people from using misc.

Just for the record, BibXML service users don’t really choose a source to use. What we do is we check all available sources and we put together an item based on that data. So it’s on us if we want to not use `misc` (just we can’t do it when it contains data in excess to what authoritative sources make available).

Here’s how this entry looks: https://dev.bibxml.org/get-one/by-docid/?docid=W3C+xml-c14n&doctype=W3C. The info is built by combining both misc and w3c entries (per-source data at the bottom), since they are considered to represent the same resource. Same happens with xml2rfc path http://dev.bibxml.org/public/rfc/bibxml2/reference.W3C.xml-c14n.xml. As a result, users see the contributor that comes from misc, even though W3C doesn’t provide that data.

**Comment by strogonoff** [comment]
> As a last resort, we can “merge” the data between misc and W3C’s data but we don’t really want to do this for many reasons.

The way the service works is more or less by merging the data when user requests it, it happens at runtime (not at source level) so I hope the reasons you had in mind don’t apply here?
