### ISSUE TITLE
Dated W3C reference search tags

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-w3c#4]
>> With date: "W3C Recommendation JSON-LD 1.1 2019-12-12"
>> https://www.w3.org/standards/history/json-ld11

> @ronaldtse with a date it should give us only another link to the document and publication date, all other information should remain as in the last version, shouldn't it?

With a date we should give the link to the dated document, for example:

* `2020-03-16` is the "Candidate Recommendation"
* `2019-05-10` is the "Working Draft"

You can notice that in the actual documents, the metadata is also different:

* `2020-03-16` is the "Candidate Recommendation", link: https://www.w3.org/TR/2020/CR-json-ld11-20200316/

<img width="609" alt="Screen Shot 2020-03-21 at 8 07 51 AM" src="https://user-images.githubusercontent.com/11865/77214630-10651280-6b4b-11ea-9875-8c24ee2128bf.png">

* `2019-05-10` is the "Working Draft": https://www.w3.org/TR/2019/WD-json-ld11-20190510/

<img width="583" alt="Screen Shot 2020-03-21 at 8 08 35 AM" src="https://user-images.githubusercontent.com/11865/77214665-2b378700-6b4b-11ea-9836-5fbc4aa5928b.png">

* `2018-09-11` is the "First Public Working Draft": https://www.w3.org/TR/2018/WD-json-ld11-20180911/

<img width="541" alt="Screen Shot 2020-03-21 at 8 08 48 AM" src="https://user-images.githubusercontent.com/11865/77214681-32f72b80-6b4b-11ea-98ca-5d87ebc0e4f2.png">

_Originally posted by @andrew2net in https://github.com/relaton/relaton/issues/50#issuecomment-601912242_

**Comment by andrew2net** [comment]
@ronaldtse it seems workgroup and keyword are only on the search page

![image](https://user-images.githubusercontent.com/5623890/77224545-2aace980-6b67-11ea-8111-2b3608eec24a.png)

**Comment by andrew2net** [comment]
fixed by ca498d600ab6f650ec311c835fa3f4f3381119a7
