### ISSUE TITLE
Stages appear with no spaces

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-w3c#40]
`W3C wot-architecture` is being fetched with 

````
<status>    <stage>candidateRecommendation</stage>  </status>
````

This is resulting in "candidateRecommendation" appearing in the rendered citation: https://github.com/metanorma/metanorma-iso/issues/1117

**Comment by andrew2net** [comment]
Fixed https://github.com/relaton/relaton-data-w3c/blob/dd234a96eb8ea794691da89e4620f3f2d94ffc75/data/wot-architecture.yaml#L31
