### ISSUE TITLE
No W3C fetches appear to be working

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-w3c#42]
Cleared Relaton cache, tried on:

W3C REC-xml-names-20091208
W3C XML
W3C REC-json-ld11-20200716

Keep getting "no matching bibliographic records found".

You haven't released this gem since July, and the work on https://github.com/relaton/relaton-w3c/issues/38 appears unrelated. https://www.w3.org/TR/?filter-tr-name=XML is working...

**Comment by opoudjis** [comment]
This impacts metanorma-ieee testing, I am going to force release

**Comment by andrew2net** [comment]
The bug was in relation-data-w3c. @opoudjis thanks for pointed it out. Fixed.
