### ISSUE TITLE
Former editors

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-w3c#5]
Do we need to parse Former editors?
<img width="369" alt="image" src="https://user-images.githubusercontent.com/5623890/77669475-1b71d580-6f85-11ea-917d-f7b88ae845c8.png">
If yes what type of contributor shuld we use?

**Comment by ronaldtse** [comment]
@andrew2net it would be better to handle them. Maybe we can add a type of contributor as "former contributor"?

Ping @opoudjis . This will have to go into relaton-model?

**Comment by opoudjis** [comment]
Yes it will, but no need to change relaton-models, the relation can already be expressed.

````
<role type="editor">
<description>former editor</description>
</role>
````

Recall that we want to keep `role/@type` very tightly constrained, whereas the description lets us refine the 6 types of contributor as much as you want.

I really, really don't see that we need to add different types of contributors or roles here; this works fine. We will need the caveat that former editors may need to be treated separately from current editors; but usually those former editors will be included in the bibliographic entry anyway.

**Comment by opoudjis** [comment]
I can't close this issue, btw...

**Comment by ronaldtse** [comment]
Not trying to crash the party but CSA documents have roles for “contributor to 1.0”, “contributor to 2.0” etc (suppose the version now is 2.0). Maybe there is a need for slightly more complex relations here?

**Comment by opoudjis** [comment]
Exactly the same solution: "description" after all is free text.

I see the temptation to link editors to editions by expanding the metadata around the role. DO NOT. The proper way to do this is to embed those editors of previous versions into related bibliographic items:

````
<bibitem>
<contributor>
<role type="editor">
<person>CURRENT EDITOR</person>
</contributor>
<edition>2.0</edition>
....
<relation type="instance">
<bibitem>
<contributor>
<role type="editor">
<person>PREVIOUS EDITOR</person>
</contributor>
<edition>1.0</edition>
</bibitem>
</relation>
</bibitem>
````

Rendering can be made to navigate that; but making role into spaghetti helps nobody.

**Comment by ronaldtse** [comment]
> The proper way to do this is to embed those editors of previous versions into related bibliographic items.

You're right. Now the question becomes -- can a document carry the previous version's metadata?

**Comment by andrew2net** [comment]
The [document](https://www.w3.org/TR/2020/CR-json-ld11-20200316/) has Former editors:
- Manu Sporny (Digital Bazaar) (v1.0)
- Markus Lanthaler (Google) (v1.0)

but it's previous [version](https://www.w3.org/TR/2020/CR-json-ld11-20200305/) has Editors:
- Gregg Kellogg (v1.0 and v1.1)
- Pierre-Antoine Champin (LIRIS - Université de Lyon) (v1.1)
- Dave Longley (Digital Bazaar) (v1.1)

seems the former editors don't match to the editors of the previous document version.

**Comment by ronaldtse** [comment]
I'm not seeing what you mean?

https://www.w3.org/TR/2020/CR-json-ld11-20200305/
<img width="482" alt="Screen Shot 2020-03-29 at 11 14 27 PM" src="https://user-images.githubusercontent.com/11865/77852784-0ad68f00-7213-11ea-82e2-930cdc379688.png">

https://www.w3.org/TR/2020/CR-json-ld11-20200316/
<img width="510" alt="Screen Shot 2020-03-29 at 11 14 42 PM" src="https://user-images.githubusercontent.com/11865/77852794-13c76080-7213-11ea-8649-1ca0a1057d2b.png">

I only see "Markus Lanthaler (Graz University of Technology)" changing to "Markus Lanthaler (Google)".


The actual JSON-LD 1.0 document seems to be this: https://www.w3.org/TR/2014/REC-json-ld-20140116/

Linked from the latest document:
<img width="447" alt="Screen Shot 2020-03-29 at 11 17 35 PM" src="https://user-images.githubusercontent.com/11865/77852865-7b7dab80-7213-11ea-83be-4b7635d31e2a.png">

**Comment by andrew2net** [comment]
@ronaldtse you are right. "Latest Recommendation" or "Previous Recommendation" is the link to the previous version. Suppose we should include the previous version as "obsoleted" relation, do we?

**Comment by ronaldtse** [comment]
> Suppose we should include the previous version as "obsoleted" relation, do we?

Agree!

**Comment by opoudjis** [comment]
Yup, that's the way forward. A bit of pain for your traversal, because "former editor" is so much easier; but it will pay off.

In the worst case that you cannot recover the edition that the former editors were invovled with, just make up a dummy record with no edition number that this work obsoletes, and stick them in there. But it sounds like you can recover it from this presentation.
