### ISSUE TITLE
Subtitle

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-w3c#6]
Should we parse subtitle and where store it?

![image](https://user-images.githubusercontent.com/5623890/78371288-0cfc6d00-75c8-11ea-9b4e-b946539162d1.png)

**Comment by ronaldtse** [comment]
TitleType `subtitle`.

<img width="228" alt="Screen Shot 2020-04-04 at 12 19 03 AM" src="https://user-images.githubusercontent.com/11865/78382740-e52df900-7609-11ea-9467-bc0169867d5e.png">
